# Generated by Django 3.2 on 2023-02-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservations',
            new_name='Reservation',
        ),
    ]
