# Generated by Django 3.2 on 2023-02-27 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20230227_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_guests',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
